### ISSUE TITLE
new connected slave doesn't get the data

### ISSUE THREAD

**Issue by iwanbk** [yinqiwen/ardb#332]
steps:
- start ardb master
- fill few MB of data
- start ardb slave
- test read data from slave : failed

it worked fine if i use redis master and it worked fine with ardb master if i start the slave before fill the data.
master log
```
[27799] 04-19 15:08:12,995 INFO Success to open lmdb at /home/ibk/work/office/ardb-replication/master/data/lmdb
[27799] 04-19 15:08:12,995 INFO Ardb init engine:lmdb success.
[27799] 04-19 15:08:12,995 INFO Ardb will accept connections on 0.0.0.0:6379
[27799] 04-19 15:08:12,996 INFO Ardb started with version 0.9.4
[27799] 04-19 15:08:40,326 INFO [Master]Recv sync command:psync ? 0 cksm 0 engine lmdb
[27799] 04-19 15:08:40,326 INFO Accept slave ip=127.0.0.1,port=6380
[27799] 04-19 15:08:40,326 WARN Create snapshot for full resync for slave replid:? offset:0 cksm:0, while current WAL runid:cbe28fb06639f517f0e7606f6bb7a6754abf794e offset:200006713 cksm:12737470374050599689
[27799] 04-19 15:08:40,326 INFO Close write latch for snapshot save preparing start.
[27799] 04-19 15:08:41,327 INFO Open write latch for snapshot save preparing complete.
[27799] 04-19 15:08:41,728 INFO Backup dump finished.
[27799] 04-19 15:08:41,728 INFO Cost 1s to save snapshot file with type:backup.
[27799] 04-19 15:08:41,728 INFO Snapshot dump success
```

slave's log
```
[27820] 04-19 15:08:28,318 INFO Success to open lmdb at /home/ibk/work/office/ardb-replication/slave/data/lmdb
[27820] 04-19 15:08:28,318 INFO Ardb init engine:lmdb success.
[27820] 04-19 15:08:28,319 INFO Ardb will accept connections on 0.0.0.0:6380
[27820] 04-19 15:08:28,320 INFO Ardb started with version 0.9.4
[27820] 04-19 15:08:40,325 INFO [Slave]Connecting master 127.0.0.1:6379
[27820] 04-19 15:08:40,325 INFO [Slave]Remote master is an ardb instance.
[27820] 04-19 15:08:40,326 INFO Send psync ? 0 cksm 0 engine lmdb
[27820] 04-19 15:08:40,327 INFO Recv psync reply:FULLBACKUP cbe28fb06639f517f0e7606f6bb7a6754abf794e 200006713 12737470374050599689
[27820] 04-19 15:08:40,327 INFO [Slave]Create sync backup path:/home/ibk/work/office/ardb-replication/slave/backup/sync-lmdb-backup.200006713.12737470374050599689.1492589320.tmp
[27820] 04-19 15:08:41,728 INFO Backup file: sync success.
[27820] 04-19 15:08:41,728 INFO Backup sync success.
[27820] 04-19 15:08:41,728 INFO Start loading snapshot:/home/ibk/work/office/ardb-replication/slave/backup/sync-lmdb-backup.200006713.12737470374050599689.1492589320
[27820] 04-19 15:08:41,730 INFO Success to open lmdb at /home/ibk/work/office/ardb-replication/slave/data/lmdb
[27820] 04-19 15:08:41,829 INFO Backup restore finished.
[27820] 04-19 15:08:41,829 INFO Cost 0.10s to load snapshot file with type:backup.
[27820] 04-19 15:08:41,829 INFO Start to replay wal from sync offset:200006713 & wal end offset:200006713
[27820] 04-19 15:08:41,829 INFO Complete replay wal with sync offset:200006713 & wal end offset:200006713
[27820] 04-19 15:08:41,829 INFO Add cached snapshot:sync-lmdb-backup.200006713.12737470374050599689.1492589320
[27820] 04-19 15:08:42,329 WARN Remove snapshot:/home/ibk/work/office/ardb-replication/slave/backup/sync-lmdb-backup.200006713.12737470374050599689.1492589320 since it's too old.
[27820] 04-19 15:08:42,329 WARN Remove snapshot file:/home/ibk/work/office/ardb-replication/slave/backup/sync-lmdb-backup.200006713.12737470374050599689.1492589320

```

**Comment by iwanbk** [comment]
```
it worked fine if i use redis master
```
the difference is, when using redis as master, slave got `FULLRESYNC` instead of `FULLBACKUP`

**Comment by iwanbk** [comment]
rocksdb engine give me more info about this
```
ERROR Failed to backup rocksdb for reason:NotFound: /root/repl-ardb/slave/backup/sync-rocksdb-backup.200006713.12737470374050599689.1492661173/meta is missing
```

Full log
```
[18673] 04-20 04:05:57,126 INFO [RocksDB]DB pointer 0x7f65363fb000
[18673] 04-20 04:05:57,127 INFO Ardb init engine:rocksdb success.
[18673] 04-20 04:05:57,129 INFO Ardb will accept connections on 0.0.0.0:6380
[18673] 04-20 04:05:57,130 INFO Ardb started with version 0.9.4
[18673] 04-20 04:06:13,138 INFO [Slave]Connecting master 127.0.0.1:6379
[18673] 04-20 04:06:13,138 INFO [Slave]Remote master is an ardb instance.
[18673] 04-20 04:06:13,138 INFO Send psync ? 0 cksm 0 engine rocksdb
[18673] 04-20 04:06:13,140 INFO Recv psync reply:FULLBACKUP 2c3f40ea78fb268fadcebe8bc868211761896405 200006713 12737470374050599689
[18673] 04-20 04:06:13,140 INFO [Slave]Create sync backup path:/root/repl-ardb/slave/backup/sync-rocksdb-backup.200006713.12737470374050599689.1492661173.tmp
[18673] 04-20 04:06:21,450 INFO Backup file: sync success.
[18673] 04-20 04:06:21,450 INFO Backup sync success.
[18673] 04-20 04:06:21,450 INFO Start loading snapshot:/root/repl-ardb/slave/backup/sync-rocksdb-backup.200006713.12737470374050599689.1492661173
[18673] 04-20 04:06:21,451 ERROR Failed to backup rocksdb for reason:NotFound: /root/repl-ardb/slave/backup/sync-rocksdb-backup.200006713.12737470374050599689.1492661173/meta is missing
[18673] 04-20 04:06:21,452 INFO [RocksDB]RocksDB version: 5.0.2
```

**Comment by yinqiwen** [comment]
@iwanbk  the latest commit fix the wrong deletion  for synced snapshot, which would fix the issue for rocksdb.  for lmdb, there is another issue for the backup implement which need more investigation.

**Comment by yinqiwen** [comment]
@iwanbk lastest commit just fix the lmdb issue

**Comment by iwanbk** [comment]
@yinqiwen thanks for the fix.
it still failed for me using lmdb.

for rocksdb, it failed to build in ubuntu 16.04. undefined reference to LZ4_***.
Yep, i've liblz4-dev installed
```
::char_traits<char>, std::allocator<char> >*, rocksdb::Slice const&)':
/root/ardb/deps/rocksdb-5.2.1/./util/compression.h:665: undefined reference to `LZ4_compressBound'
/root/ardb/deps/rocksdb-5.2.1/./util/compression.h:670: undefined reference to `LZ4_createStreamHC'
/root/ardb/deps/rocksdb-5.2.1/./util/compression.h:671: undefined reference to `LZ4_resetStreamHC'
/root/ardb/deps/rocksdb-5.2.1/./util/compression.h:676: undefined reference to `LZ4_loadDictHC'
/root/ardb/deps/rocksdb-5.2.1/./util/compression.h:681: undefined reference to `LZ4_compress_HC_continue'
/root/ardb/deps/rocksdb-5.2.1/./util/compression.h:687: undefined reference to `LZ4_freeStreamHC'
/root/ardb/src/../deps/rocksdb-5.2.1/librocksdb.a(block_based_table_builder.o): In function `rocksdb::LZ4_Compress(rocksdb::CompressionOptions const&, unsigned int, char const*, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, rocksdb::Slice)':
/root/ardb/deps/rocksdb-5.2.1/./util/compression.h:554: undefined reference to `LZ4_loadDict'
collect2: error: ld returned 1 exit status
Makefile:280: recipe for target 'test' failed
make[1]: *** [test] Error 1
make[1]: Leaving directory '/root/ardb/src'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
root@5f9cd907f352:~/ardb# dpkg -l | grep lz4
ii  liblz4-1:amd64             0.0~r131-2ubuntu2               amd64        Fast LZ compression algorithm library - runtime
ii  liblz4-1-dbg               0.0~r131-2ubuntu2               amd64        Fast LZ compression algorithm library - Debugging Symbols
ii  liblz4-dev:amd64           0.0~r131-2ubuntu2               amd64        Fast LZ compression algorithm library - development files
ii  liblz4-tool                0.0~r131-2ubuntu2               amd64        Fast LZ compression algorithm library - tool
```

**Comment by iwanbk** [comment]
I managed to compile the rocksdb version, but slave still failed to sync with same error message (meta is missing)

**Comment by yinqiwen** [comment]
@iwanbk  u need to add -llz4 in src/makefile to link lz4 since rocksdb requires it.

**Comment by iwanbk** [comment]
```
@iwanbk u need to add -llz4 in src/makefile to link lz4 since rocksdb requires it.
```
thanks. my solution was uninstall the liblz4-dev :-D

**Comment by yinqiwen** [comment]
@iwanbk  for lmdb, the latest  slave log:

      

> [27502] 04-20 20:37:09,238 WARN Read DB ID faile with MDB_NOTFOUND: No matching key/data pair found
[27502] 04-20 20:37:09,239 INFO Success to open lmdb at /home/wqy/share/ardb/slave/data/lmdb
[27502] 04-20 20:37:09,239 INFO Ardb init engine:lmdb success.
[27502] 04-20 20:37:09,242 INFO Ardb will accept connections on 0.0.0.0:26379
[27502] 04-20 20:37:09,244 INFO Ardb started with version 0.9.4
[27502] 04-20 20:37:13,243 INFO [Slave]Connecting master 127.0.0.1:16379
[27502] 04-20 20:37:13,244 INFO [Slave]Remote master is an ardb instance.
[27502] 04-20 20:37:13,245 INFO Send psync ? 0 cksm 0 engine lmdb
[27502] 04-20 20:37:13,246 INFO Recv psync reply:FULLBACKUP 87edfb5e554837819c30220ab5a240162627a4ad 11238325 4442536011336687293
[27502] 04-20 20:37:13,247 INFO [Slave]Create sync backup path:/home/wqy/share/ardb/slave/backup/sync-lmdb-backup.11238325.4442536011336687293.1492742233.tmp
[27502] 04-20 20:37:13,248 INFO Backup file:data.mdb sync success.
[27502] 04-20 20:37:13,250 INFO Backup sync success.
[27502] 04-20 20:37:13,252 INFO Start loading snapshot:/home/wqy/share/ardb/slave/backup/sync-lmdb-backup.11238325.4442536011336687293.1492742233
[27502] 04-20 20:37:13,255 INFO Open db:0 success.
[27502] 04-20 20:37:13,256 INFO Open db:__TTL_DB__ success.
[27502] 04-20 20:37:13,257 WARN Read DB ID faile with MDB_NOTFOUND: No matching key/data pair found
[27502] 04-20 20:37:13,258 INFO Success to open lmdb at /home/wqy/share/ardb/slave/data/lmdb
[27502] 04-20 20:37:13,353 INFO Backup restore finished.
[27502] 04-20 20:37:13,353 INFO Cost 0.10s to load snapshot file with type:backup.
[27502] 04-20 20:37:13,353 INFO Start to replay wal from sync offset:11238325 & wal end offset:11238325
[27502] 04-20 20:37:13,353 INFO Complete replay wal with sync offset:11238325 & wal end offset:11238325
[27502] 04-20 20:37:13,353 INFO Add cached snapshot:sync-lmdb-backup.11238325.4442536011336687293.1492742233

**Comment by iwanbk** [comment]
@yinqiwen  below is my log for lmdb.
the difference between yours is this line
```
INFO Backup file: sync success.
```
your log
```
INFO Backup file:data.mdb sync success.
```

full log
```
[1354] 04-21 02:45:52,608 WARN Read DB ID faile with MDB_NOTFOUND: No matching key/data pair found
[1354] 04-21 02:45:52,608 INFO Success to open lmdb at /root/g8os/ardb-replication/slave/data/lmdb
[1354] 04-21 02:45:52,608 INFO Ardb init engine:lmdb success.
[1354] 04-21 02:45:52,609 INFO Ardb will accept connections on 0.0.0.0:6380
[1354] 04-21 02:45:52,609 INFO Ardb started with version 0.9.4
[1354] 04-21 02:46:23,632 INFO [Slave]Connecting master 127.0.0.1:6379
[1354] 04-21 02:46:23,633 INFO [Slave]Remote master is an ardb instance.
[1354] 04-21 02:46:23,633 INFO Send psync ? 0 cksm 0 engine lmdb
[1354] 04-21 02:46:23,634 INFO Recv psync reply:FULLBACKUP 13266d5875da6635b4d5485ff8d1ba3c7dc84975 200006713 12737470374050599689
[1354] 04-21 02:46:23,634 INFO [Slave]Create sync backup path:/root/g8os/ardb-replication/slave/backup/sync-lmdb-backup.200006713.12737470374050599689.1492742783.tmp
[1354] 04-21 02:46:25,036 INFO Backup file: sync success.
[1354] 04-21 02:46:25,036 INFO Backup sync success.
[1354] 04-21 02:46:25,036 INFO Start loading snapshot:/root/g8os/ardb-replication/slave/backup/sync-lmdb-backup.200006713.12737470374050599689.1492742783
[1354] 04-21 02:46:25,041 WARN Read DB ID faile with MDB_NOTFOUND: No matching key/data pair found
[1354] 04-21 02:46:25,041 INFO Success to open lmdb at /root/g8os/ardb-replication/slave/data/lmdb
[1354] 04-21 02:46:25,137 INFO Backup restore finished.
[1354] 04-21 02:46:25,137 INFO Cost 0.10s to load snapshot file with type:backup.
[1354] 04-21 02:46:25,137 INFO Start to replay wal from sync offset:200006713 & wal end offset:200006713
[1354] 04-21 02:46:25,137 INFO Complete replay wal with sync offset:200006713 & wal end offset:200006713
[1354] 04-21 02:46:25,137 INFO Add cached snapshot:sync-lmdb-backup.200006713.12737470374050599689.1492742783
```

**Comment by yinqiwen** [comment]
@iwanbk  is the master server latest version? and can u check the synced dir `/root/g8os/ardb-replication/slave/backup/sync-lmdb-backup.200006713.12737470374050599689.1492742783` if it's empty without any file?

**Comment by iwanbk** [comment]
```
@iwanbk is the master server latest version
```
Yep
```
and can u check the synced dir /root/g8os/ardb-replication/slave/backup/sync-lmdb-backup.200006713.12737470374050599689.1492742783 if it's empty without any file?
```
also yes :)

**Comment by yinqiwen** [comment]
@iwanbk  the synced data file from master should not be empty event there is no data in master server. is there any error info in master server?

**Comment by iwanbk** [comment]
no error info in master
``
root@6639e3b121a5:~/g8os/ardb-replication# rm -rf master && ./ardb-server conf-master.conf                         
[1658] 04-21 03:42:27,821 WARN Read DB ID faile with MDB_NOTFOUND: No matching key/data pair found
[1658] 04-21 03:42:27,821 INFO Success to open lmdb at /root/g8os/ardb-replication/master/data/lmdb
[1658] 04-21 03:42:27,821 INFO Ardb init engine:lmdb success.
[1658] 04-21 03:42:27,822 INFO Ardb will accept connections on 0.0.0.0:6379
[1658] 04-21 03:42:27,822 INFO Ardb started with version 0.9.4
[1658] 04-21 03:42:38,759 INFO [Master]Recv sync command:psync ? 0 cksm 0 engine lmdb
[1658] 04-21 03:42:38,759 INFO Accept slave ip=127.0.0.1,port=6380
[1658] 04-21 03:42:38,759 WARN Create snapshot for full resync for slave replid:? offset:0 cksm:0, while current WAL runid:1f6ad83b56a1ec5eb722a729cbcafae7e4b28641 offset:200006713 cksm:12737470374050599689
[1658] 04-21 03:42:38,760 WARN ibk:backup dump
[1658] 04-21 03:42:38,760 INFO Close write latch for snapshot save preparing start.
[1658] 04-21 03:42:39,761 INFO Open write latch for snapshot save preparing complete.
[1658] 04-21 03:42:40,162 INFO Backup dump finished.
[1658] 04-21 03:42:40,162 INFO Cost 2s to save snapshot file with type:backup.
[1658] 04-21 03:42:40,162 INFO Snapshot dump success
```

FYI, it worked well in these setups:
-  redis master - ardb slave 
- ardb master - redis slave
- ardb master - ardb slave, if the slave started before we fill the data.

**Comment by iwanbk** [comment]
```
and can u check the synced dir /root/g8os/ardb-replication/slave/backup/sync-lmdb-backup.200006713.12737470374050599689.1492742783 if it's empty without any file?
```
it is also empty in rocksdb

**Comment by yinqiwen** [comment]
at master, is the server have write permission in dir `/root/g8os/ardb-replication/master`?   the dir is the place where master created sync snapshot files.

**Comment by iwanbk** [comment]
yes, it is a newly created dir created by master itself.

**Comment by iwanbk** [comment]
hi @yinqiwen.
really sorry about the noise, i tried it on fresh VPS and it just worked.

I'll try it with bigger data

**Comment by iwanbk** [comment]
thanks it works
