### ISSUE TITLE
 Ardb does not compile in OSX (mavericks, Xcode 5.0.2)

### ISSUE THREAD

**Issue by sscarduzio** [yinqiwen/ardb#25]
Hi, I'm trying to compile master branch from source, but I cannot get this error passed:

```
$ make
cd src && /Applications/Xcode.app/Contents/Developer/usr/bin/make all
g++ -c -Wall -g  -O2  -fPIC -D__STDC_FORMAT_MACROS -DARDB_VERSION='"0.6.0"'  -I./ -I/tmp/ardb/src/../deps/cpp-btree -I/tmp/ardb/src/../deps/lua/src -I/tmp/ardb/src/../deps/snappy-1.1.1 -I/tmp/ardb/src/../deps/zookeeper-3.4.5/include -I/tmp/ardb/src/../deps/zookeeper-3.4.5/generated -I/tmp/ardb/src/../deps/leveldb-1.16.0/include ardb.cpp -o ardb.o
In file included from ardb.cpp:30:
In file included from ./ardb.hpp:38:
In file included from ./common.hpp:171:
In file included from /tmp/ardb/src/../deps/cpp-btree/btree_set.h:27:
/tmp/ardb/src/../deps/cpp-btree/btree.h:114:10: fatal error: 'tr1/type_traits' file not found
#include CPP_BTREE_TYPE_TRAITS_HEADER
         ^
/tmp/ardb/src/../deps/cpp-btree/btree_config.h:32:40: note: expanded from macro 'CPP_BTREE_TYPE_TRAITS_HEADER'
  #define CPP_BTREE_TYPE_TRAITS_HEADER <tr1/type_traits>
                                       ^
1 error generated.
make[1]: *** [ardb.o] Error 1
make: *** [all] Error 2
```

I got stuck, could you please help or provide documentation for the procedure under OSX?
