### ISSUE TITLE
Can't compile with gcc++ 4.8.1

### ISSUE THREAD

**Issue by ghost** [yinqiwen/ardb#88]
Can't compile leveldb... i've tried downgrading to level1.14 and the problem still persist...

db/db_iter.cc:107:3: error: ‘ssize_t’ does not name a type
   ssize_t RandomPeriod() {
   ^

compiled with gcc4.4... works.
