### ISSUE TITLE
lmdb engine wont compile on gcc 4.8

### ISSUE THREAD

**Issue by pedigree** [yinqiwen/ardb#41]
storage_engine=lmdb make fails with the following

<code>
g++ -c -Wall -g -O2 -fPIC -fpermissive -D__STDC_FORMAT_MACROS -DARDB_VERSION='"0.7.1"'  -D__USE_LMDB__ -I./ -I/home/gateway/dev/ardb/src/../deps/cpp-btree -I/home/gateway/dev/ardb/src/../deps/lua/src -I/home/gateway/dev/ardb/src/../deps/snappy-1.1.1 -I/home/gateway/dev/ardb/src/../deps/zookeeper-3.4.5/include -I/home/gateway/dev/ardb/src/../deps/zookeeper-3.4.5/generated -I/home/gateway/dev/ardb/src/../deps/mdb-mdb/libraries/liblmdb engine/lmdb_engine.cpp -o engine/lmdb_engine.o
engine/lmdb_engine.cpp:321:45: warning: declaration of ‘virtual void ardb::LMDBIterator::Seek(const ardb::Slice&)’ outside of class is not definition [-fpermissive]
  void LMDBIterator::Seek(const Slice& target);
                                             ^
engine/lmdb_engine.cpp:322:2: error: expected unqualified-id before ‘{’ token
  {
  ^
</code>
